# Generated by Django 2.2.1 on 2019-05-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='')),
                ('event_name', models.CharField(max_length=40)),
                ('venue', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('charges', models.CharField(max_length=40)),
                ('contact', models.IntegerField()),
                ('description', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('comment', models.CharField(max_length=40)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='current.Event')),
            ],
        ),
    ]
